// 14 module (mỗi module = 1 sub-folder keyword trong Papers_keywords). ready = bản VI xong; readyEn = bản EN xong.
window.THESIS_MODULES = [
  {n:'01', slug:'01-productive-failure', title:'Productive Failure', sub:'Vật lộn trước, học sau', title_en:'Productive Failure', sub_en:'Struggle first, learn after', src:'Kapur 2008, 2014, 2016', ico:'🧗', ready:true, readyEn:true},
  {n:'02', slug:'02-cognitive-load', title:'Cognitive Load Theory', sub:'Trí nhớ làm việc có hạn', title_en:'Cognitive Load Theory', sub_en:'Working memory is limited', src:'Sweller 1988, 1998; Kirschner 2006', ico:'🧠', ready:true, readyEn:true},
  {n:'03', slug:'03-cognitive-apprenticeship', title:'Cognitive Apprenticeship & Scaffolding', sub:'Giúp rồi rút dần', title_en:'Cognitive Apprenticeship & Scaffolding', sub_en:'Help, then fade', src:'Collins 1987, 1991; Brown 1989; Wood 1976', ico:'🪜', ready:true, readyEn:true},
  {n:'04', slug:'04-self-regulated-learning', title:'Self-Regulated Learning', sub:'Kế hoạch, thực hiện, phản tư', title_en:'Self-Regulated Learning', sub_en:'Forethought, performance, reflection', src:'Zimmerman 1990, 2002; Puustinen 2001', ico:'🔄', ready:true, readyEn:true},
  {n:'05', slug:'05-metacognition', title:'Metacognition', sub:'Biết mình đang biết gì', title_en:'Metacognition', sub_en:'Knowing what you know', src:'Flavell 1979; Schraw 1994; Garner 1989; Rhodes 2019', ico:'🪞', ready:true, readyEn:true},
  {n:'06', slug:'06-self-efficacy', title:'Self-Efficacy', sub:'Niềm tin vào năng lực bản thân', title_en:'Self-Efficacy', sub_en:'Belief in your own capability', src:'Bandura 1977', ico:'💪', ready:true, readyEn:true},
  {n:'07', slug:'07-active-learning', title:'Active Learning', sub:'Từ nghe sang làm (ICAP)', title_en:'Active Learning', sub_en:'From listening to doing (ICAP)', src:'Freeman 2014; Chi & Wylie 2014', ico:'✋', ready:true, readyEn:true},
  {n:'08', slug:'08-cognitive-offloading', title:'Cognitive Offloading', sub:'Giao việc cho công cụ', title_en:'Cognitive Offloading', sub_en:'Handing thinking to tools', src:'Risko 2016; Sparrow 2011; Gerlich 2025; Lee 2025; Kosmyna 2025', ico:'📤', ready:true, readyEn:true},
  {n:'09', slug:'09-cognitive-augmentation', title:'Cognitive Augmentation', sub:'AI khuếch đại chứ không thay thế', title_en:'Cognitive Augmentation', sub_en:'AI amplifies, not replaces', src:'Engelbart 1962; Licklider 1960; Clark & Chalmers 1998', ico:'🦾', ready:false, readyEn:false},
  {n:'10', slug:'10-appropriate-reliance', title:'Appropriate Reliance & Calibrated Trust', sub:'Tin đúng mức', title_en:'Appropriate Reliance & Calibrated Trust', sub_en:'Trusting the right amount', src:'Lee & See 2004; Parasuraman 1997; Skitka 1999', ico:'⚖️', ready:false, readyEn:false},
  {n:'11', slug:'11-tam', title:'Technology Acceptance Model (TAM)', sub:'Hữu ích và dễ dùng', title_en:'Technology Acceptance Model (TAM)', sub_en:'Useful and easy to use', src:'Davis 1985, 1989; Davis, Bagozzi & Warshaw 1989', ico:'🧩', ready:false, readyEn:false},
  {n:'12', slug:'12-utaut', title:'UTAUT', sub:'Mô hình hợp nhất chấp nhận công nghệ', title_en:'UTAUT', sub_en:'Unified model of technology acceptance', src:'Venkatesh 2003', ico:'🔗', ready:false, readyEn:false},
  {n:'13', slug:'13-experimental-design', title:'Quasi-experiment & RCT', sub:'Thiết kế thực nghiệm', title_en:'Quasi-experiment & RCT', sub_en:'Experimental design', src:'Schulz 2011 (CONSORT)', ico:'🧪', ready:false, readyEn:false},
  {n:'14', slug:'14-ai-in-education', title:'AI trong giáo dục có trách nhiệm', sub:'Bằng chứng và đạo đức', title_en:'Responsible AI in Education', sub_en:'Evidence and ethics', src:'Bastani 2025; Kestin 2025; Kasneci 2023; Holmes 2022; Jobin 2019', ico:'🎓', ready:false, readyEn:false}
];
